// Generated by CoffeeScript 1.8.0
(function() {
  var Migrator, Path, migrator;

  Path = require('path');

  Migrator = require("./migrator");

  migrator = new Migrator('http://admin:userssuck@localhost:5984/continuum', Path.join(__dirname, 'example'));

  migrator.updateIfNecessary();

}).call(this);
