// Generated by CoffeeScript 1.8.0
(function() {
  var Migrator, crypto, fs, hasher, nano, path;

  fs = require('fs');

  nano = require('nano');

  path = require('path');

  crypto = require('crypto');

  hasher = crypto.createHash('sha256');

  Migrator = (function() {
    function Migrator(uri, baseDirectory) {
      this.uri = uri;
      this.baseDirectory = baseDirectory;
      console.log(this.uri, this.baseDirectory);
      this.db = nano(this.uri);
    }

    Migrator.prototype.updateIfNecessary = function() {
      var file, files, id, _i, _len, _results;
      files = fs.readdirSync(this.baseDirectory);
      console.log(files);
      _results = [];
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        file = files[_i];
        id = "_design/" + path.basename(file, '.js');
        _results.push(this.db.get(id, (function(_this) {
          return function(err, doc) {
            var absFilePath, hash, obj, views;
            console.log(_this.baseDirectory, file);
            absFilePath = path.join(_this.baseDirectory, file);
            obj = JSON.parse(fs.readFileSync(absFilePath, 'utf8'));
            views = JSON.stringify(obj);
            console.log("id", id);
            console.log(views);
            hasher.update(views, 'utf8');
            hash = hasher.digest('hex');
            if (err) {
              doc = {
                _id: id
              };
              doc.language = 'javascript';
              doc.hash = hash;
              doc.views = views;
              return _this.db.insert(doc, function(err, ret) {
                console.log(err);
              });
            } else if (doc && doc.hash !== hash) {
              doc.views = views;
              doc.hash = hash;
              return _this.db.insert(doc, function(err, ret) {
                return console.log(err);
              });
            }
          };
        })(this)));
      }
      return _results;
    };

    return Migrator;

  })();

  module.exports = Migrator;

}).call(this);
